rss_urls = [
        "https://feeds.captivate.fm/techpolicypress/",
        "https://edtechprinciples.com/feed/"
        "https://www.siia.net/feed/",
        "https://datasociety.net/feed/"]
        # "https://www.cambridge.org/core/rss/product/id/46CDA9F399554E6B3AB5E4821C6A4B43",
        # "https://freedom-to-tinker.com/feed/",
        # "https://www.eff.org/rss/updates.xml",
        # "https://www.rand.org/topics/science-and-technology.xml",
        # "https://cset.georgetown.edu/feed/",
        # "https://epic.org/feed/",
        # "https://dig.watch/feed",
        # "https://blog.opensource.org/feed/",
        # "https://brain.ieee.org/feed/",
        # "https://policyreview.info/feed",
        # "https://digi-con.org/feed/",
        # "https://future.a16z.com/feed",
        # "https://www.meganannebrozek.com/blog-feed.xml",
        # "https://bair.berkeley.edu/blog/feed",
        # "https://navigatingairisks.substack.com/feed",
        # "https://www.alignmentforum.org/rss",
        # "https://ourdigitaldisco.substack.com/feed",
        # "https://www.forourposterity.com/blog/rss",
        # "https://www.jonstokes.com/feed",
        # "https://forum.effectivealtruism.org/feed.xml",
        # "https://futureoflife.org/feed/",
        # "https://www.marktechpost.com/feed/",
        # "http://arxiv.org/rss/cs.AI/",
        # "https://news.mit.edu/topic/mitmachine-learning-rss.xml",
        # "https://blog.ml.cmu.edu/feed/",
        # "https://epochai.org/atom.xml",
        # "https://aiimpacts.org/feed/",
        # "https://www.apolloresearch.ai/blog?format=rss",
        # "https://www.frontiersin.org/journals/artificial-intelligence/rss",
        # "https://fetchrss.com/rss/6511b03cee2f5c57f243dfd36511b01d060be640690d0182.xml",
        # "https://fetchrss.com/rss/6511b03cee2f5c57f243dfd36511b0b7dd27d610fd320fb2.xml",
        # "https://ainowinstitute.org/feed",
        # "https://medium.com/feed/@canadianinnovators",
        # "https://mlcommons.org/feed/",
        # "https://deeplearningindaba.com/feed/",
        # "https://aii-sa.co.za/feed/",
        # "https://solrashidi.substack.com/feed",
        # "https://chinai.substack.com/feed",
        # "https://garymarcus.substack.com/feed",
        # "https://www.fmai-hub.com/feed/",
        # "https://aisafetychina.substack.com/feed",
        # "https://blog.google/technology/ai/rss/",
        # "https://aisafetyexplained.substack.com/feed",
        # "https://www.planned-obsolescence.org/rss/",
        # "https://points.datasociety.net/feed",
        # "https://theprivacywhisperer.substack.com/feed",
        # "https://www.worldprivacyforum.org/feed/",
        # "https://fpf.org/feed/",
        # "https://iapp.org/rss/daily-dashboard/",
        # "https://www.nist.gov/news-events/cybersecurity/rss.xml",
        # "https://export.arxiv.org/rss/cs.CR",
        # "https://blog.google/technology/safety-security/rss/",
        # "https://5stars217.github.io/feed",
        # "https://www.iso.org/contents/data/standard/08/42/84257.detail.rss",
        # "https://www.rand.org/topics/cyber-and-data-sciences.xml"

        # Bozo articles
        # "https://api.start.me/widgets/64657916,64619065,64814145/articles" ,
        # "https://api.start.me/widgets/63871721/articles"
        #     ]